CTL9-45-51-LoginAndRegisterScreen
draganaZdravkovic/Cocktails9 pull request #14
Opened 2023-12-19 13:39 UTC by draganaZdravkovic

Implement Login and Register. Connect user with it's favorites cocktails.

2023-12-19 15:47 UTC, Levi9Daniel requested changes

2023-12-19 15:47 UTC, Levi9Daniel commented on app/src/main/java/com/example/cocktails9/ui/fragment/authentication/LoginFragment.kt
> +        if (email.isEmpty()
Please use AS offered solution to remove if statement

2023-12-19 15:47 UTC, Levi9Daniel commented on app/src/main/java/com/example/cocktails9/ui/fragment/favorites/FavoritesFragment.kt
> +    @RequiresApi(Build.VERSION_CODES.N)
Remove the annotation since it is not needed. Please do this for the whole method call chain form here until the view model methods

2023-12-19 15:47 UTC, Levi9Daniel commented on app/src/main/java/com/example/cocktails9/ui/fragment/favorites/viewmodel/FavoritesViewModel.kt
> +//        val s = repository.getFavorites(userEmail).map {
Please remove commented code

2023-12-19 15:47 UTC, Levi9Daniel commented on app/src/main/java/com/example/cocktails9/ui/fragment/profile/ProfileFragment.kt
> +    private lateinit var sharedPreferences: SharedPreferences
Plase use sharedPref inside a VM.

2023-12-19 15:47 UTC, Levi9Daniel commented on app/src/main/java/com/example/cocktails9/ui/fragment/profile/ProfileFragment.kt
> +        binding.etEmail.setText(
Provide needed data through liveData from VM. Can use AuthView Model for this

2023-12-19 17:41 UTC, draganaZdravkovic commented on app/src/main/java/com/example/cocktails9/ui/fragment/profile/ProfileFragment.kt
> +        binding.etEmail.setText(
Do you mean for userEmail? And if so, why do I need LiveData for userEmail when userEmail cannot be changed?

2023-12-20 10:38 UTC, Levi9Daniel approved these changes

2023-12-20 10:38 UTC, merged